### PR TITLE
a little step forwards

### PR DESCRIPTION
**Pull request by schweigel**
solved #10
make changes for #9, but not finally

### CODE REVIEW

**Comment by Apollon77** [comment]
shopuld we release a new version after the fix or do you have more?

**Comment by schweigel** [comment]
Hi, I solved issue #9 too. That's all I have now.

**Comment by GermanBluefox** [comment]
@schweigel Can you please test my changes? And if everything ok, I will publish it.

**Comment by Apollon77** [comment]
@GermanBluefox (review comments):
* you implememted compact mode support, but the opened net server is not closed, there is no "unload". This will break compact mode
* There is no error handling for the opened net server, could also crash the compact controller
* no reconnection handling in adapter (ok, no real blocker)
* Admin UI not translated (also no blocker)
* The code structure with the onStateChange in https://github.com/ioBroker/ioBroker.wolf/blob/master/wolf.js#L516 ... will that mean we register a new statChange handler with every connection? Is this really intended?

**Comment by GermanBluefox** [comment]
- unload implemented
- error handling added
- re-connection is not required, because it is server
- Admin translated
- onStateChange modified.

**Comment by schweigel** [comment]
> @schweigel Can you please test my changes? And if everything ok, I will publish it.

Hi,

I updated to your version 1.1.1. I take a look at the values and they look the same as my version.
But I figured out that my changes for the Date value are still not correct. It worked in november but in december it shows january 2020. 😕 

So for me its better than before, but not perfect. I would try to solve this, but I don't know when I will found time to to this.

**Comment by Apollon77** [comment]
I merged your fix too  :-)

**Pull request merged**
