### PR TITLE
Made changes to get the adapter to work in my setup.

### PR DESCRIPTION
**Pull request by Dark-Tower-Coder**

### CODE REVIEW

**Comment by Apollon77** [comment]
What exactly brings this PR beside Renaming things? I fdo not get that really? What is fixed? What is "your setup"? Why the PR shows some empty files?

**Comment by Dark-Tower-Coder** [comment]
Hi.
I'm trying to bring a little light into the dark.
But first of all, this was my first PR and I'm an absolute beginner in this field.

My setup:
Wolf heating + Wolf Solar + Wolf CWL
I installed the ISM8i module (HW version: 1.0, FW version: 1.70) on my heater and couldn't create any data points with the ioBroker adapter.
Just like some other users (see Issues).

1st change
Then I tried to analyze the code and noticed that in main.js in
function createServer (adapter) {
...
 if (adapter.config.devices [device] === 'Auto') {
...
}}
(Line 654)
was always "false".
After I adjusted the names I always had "true" for the correct data points and the data points were correctly created in the ioBroker and I continuously received correct data.

2nd change
In datapoint.json I have adjusted line 1473, because the name did not match the official name from the documentation.

3rd change
I also did not receive any data for data point 149 because the query for this was carried out in the wrong place in main.js. I created / adjusted lines 244-253 accordingly.


I don't know why I have empty files in PR.
Sorry for the inconvenience, I promise I'll get better ;-)

**Comment by FRAMELIFTER** [comment]
Hi.
I was trying to get the wolf adapter running for 3 days now ... nothing worked. Everytime i changed the ISM8i config i needed to restart the "Heizung" ;)
Then i thought i give it (https://github.com/Dark-Tower-Coder/ioBroker.wolf) a try, installed and all the data came up instantly.

Thanks for your fork & work @Dark-Tower-Coder

**Comment by Dark-Tower-Coder** [comment]
> Hi.
> I was trying to get the wolf adapter running for 3 days now ... nothing worked. Everytime i changed the ISM8i config i needed to restart the "Heizung" ;)
> Then i thought i give it (https://github.com/Dark-Tower-Coder/ioBroker.wolf) a try, installed and all the data came up instantly.
> 
> Thanks for your fork & work @Dark-Tower-Coder 

Could you write once which ISM8i module you have? So which HW and FW versions and which heating and whether there are other devices via bus.

**Comment by FRAMELIFTER** [comment]
Yes of course I can;
ISM8i, HW1.0 FW 1.70
image

I think i dont get all the possible Datapoints i should have.
I only have a CGS-2-24/200L with an BM-2.
The only Datapoints i get are the following; i thougt i can get ever parameter to control the complete Heater:
image
image

**Comment by Dark-Tower-Coder** [comment]
Are you missing certain data points?
If I look at the [documentation](https://www.wolf.eu/fileadmin/Wolf_Profi/Downloads/Montage-Bedienungsanleitungen/Regelungen/Zubehoer/3064356_201611_ISM8i_Montage-u.Bedienungsanleitung.pdf), I would say that you have all the data points listed that affect your heating + your control module.
Heating: DP 1-13 + 197-199
BM-2: DP 53-66

**Comment by Dark-Tower-Coder** [comment]
@Apollon77 
Is there something missing in this PR?
Or should I close it again?

**Comment by Apollon77** [comment]
I'm still confused abotu the changes and emoty file and honestly @GermanBluefox need to say something here because I cannot "see" what the changes really mean

**Comment by Dark-Tower-Coder** [comment]
I can't really explain it either.
But the one method expects most names with _t. Without this, the correct data points will not be recognized and the received data will not be processed any further.
Why that's so, I do not know. I suspect that the names with _t come from the GUI. But I'm too new to this field to judge.

I installed and tried out many different versions of your adapter on two devices. Neither version worked for me.
But my changes seem to have worked immediately with @FRAMELIFTER ...

**Comment by booleeny** [comment]
> Hi. I was trying to get the wolf adapter running for 3 days now ... nothing worked. Everytime i changed the ISM8i config i needed to restart the "Heizung" ;) Then i thought i give it (https://github.com/Dark-Tower-Coder/ioBroker.wolf) a try, installed and all the data came up instantly.
> 
> Thanks for your fork & work @Dark-Tower-Coder

Hi, same here with the same setup. ISM8i with HW 1.0 FW. 1.70. I tried the 'official' adapter with the latest version 1.3.4 and received no datapoints. After getting the fork (https://github.com/Dark-Tower-Coder/ioBroker.wolf) into iobroker and restartet the heating (red Wolf logo on the front) all datapoints came in. Please get this fork/pull request in merge.

**Comment by Apollon77** [comment]
Then I would say I declare it as "prooved by community" :-)

**Comment by Apollon77** [comment]
But as said I need to somehow sort ot that PR "mess" ;-)

**Review by Dark-Tower-Coder — COMMENTED** [review]
Files without changes, marked as viewed.

**Comment by Dark-Tower-Coder** [comment]
After cleaning up the many unprocessed files, the PR is ready to check again.
I hope everything fits now. :-)

**Comment by Apollon77** [comment]
@Dark-Tower-Coder Why closed? I know it is on me to merge, but why closed?

**Comment by Apollon77** [comment]
Or do you open a new PR?

**Comment by Dark-Tower-Coder** [comment]
To be honest, I don't know if I did it right.
Since it took so long I assumed I did something wrong.

I worked a bit on the code today and implemented new functions and a bugfix.
Will push it right away.
Then I can still do a PR.

**Pull request closed without merging**
